version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./files:/app/files
      - ./data:/app/data
    environment:
      - BASE_PATH=/app
      - SERVER_PORT=8080 